spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_todo?createDatabaseIfNotExist=true
    username: root

jpa:
  show-sql: true
server:
  port: 8080
